### ISSUE TITLE
No test :-(

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-modelangelo#3]
Hi @pconesa, I see this protocol has no test.  

   Do you have one? Otherwise I volunteer to  create one

**Comment by pconesa** [comment]
You are welcome to create one..  I couldn't find one suitable to be automatically tested in buildbot.

Carlos Oscar though about hemoglobin? Would this work and be short?

**Comment by rmarabini** [comment]
hi @pconesa 

   I will find a good candidate. Hemoglobine is a bit large for a test. Another point, I do not see the possibility to use as input several sequences.  Do you have the code available?

**Comment by pconesa** [comment]
OK @pconesa, I will implement it. By the way, the test specimen is going to be emb-0406. I think is the smallest protein solved by cryo-em.

> This is not implemented...

**Comment by rmarabini** [comment]
Hi @pconesa, I think this is ready

 * added sequence list as input instead of a single sequence
 * test added
 

as far as I am concerned fill free to close this issue
